GET http://localhost:3001/api/persons/6626abba683a54f9a2985ad3

###
GET http://localhost:3001/api/persons

###
DELETE http://localhost:3001/api/persons/6626abba683a54f9a2985ad3

###
POST http://localhost:3001/api/persons
content-type: application/json


{
    "name": "jaim",
    "number": "123-2456"
}
