GET http://localhost:3001/api/persons/662331f542f64953fcbbbe5

###
GET http://localhost:3001/api/persons

###
DELETE http://localhost:3001/api/persons/6626642aa994af67f0a74ea

###
POST http://localhost:3001/api/persons
content-type: application/json


{
    "name": "jaim",
    "number": "12341-2456"
}
